name: "lint python"
on: [push, pull_request]
jobs:
  run-py-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install apt dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools python3-venv python3-pip gcc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest-pylint
      - name: Lint with Pylint
        run: |
          find . ! -path "./.venv/*" -type f -name "*.py"  | xargs pylint --rcfile pylintrc
